x-config: &conf
  restart: always
  networks:
    - mynet   
 
x-environment: &env
    TZ: Asia/Shanghai
    PUID: "99"
    PGID: "100"        

# 上面创建锚点 下面使用
services:
  jellyfin:
    image: nyanmisaka/jellyfin         # n大版jf 开箱即用
    container_name: jellyfin
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/icon.png"
      net.unraid.docker.webui: "http://[host]:8096"
    ports: 
      - "8096:8096"
    volumes:
      - /mnt/user/appdata/mydata/jf:/config      # 配置文件路径
      - /mnt/user/movie_data:/moviedata              # 媒体文件路径
      - /dev/shm/jf:/cache                           # 缓存进内存
    <<: *conf
    environment:
      <<: *env
    privileged: "true"                               # 特权模式
    devices:
      - "/dev:/dev"


  emby:
    image: linuxserver/emby
    container_name: emby
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Emby/icon.png
    ports:
      - 8097:8096
    volumes:
      - /mnt/user/appdata/mydata/emby:/config       # 配置文件路径
      - /mnt/user/movie_data:/moviedata                 # 媒体文件路径
      - /dev/shm/emby:/cache                            # 缓存进内存
    <<: *conf
    environment:
      <<: *env
    privileged: "true"
    devices:
      - "/dev:/dev"
  

  nastools:    # v3版本
    image: hsuyelin/nas-tools
    container_name: nas-tools
    labels:
      - net.unraid.docker.icon=https://i.mji.rip/2023/11/07/ff7d5b863e297051d51fa340c0ad96c2.jpeg
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/appdata/mydata/ntv3:/config          # 配置路径
      - /mnt/user/movie_data:/movie_data                   # 媒体文件和下载目录的公共的上层路径
    <<: *conf
    environment:
      <<: *env

  qbittorrent:
    image: johngong/qbittorrent
    container_name: qbittorrent
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/icon.png
    ports:
      - 8989:8989
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - /mnt/user/appdata/mydata/qb:/config             # 配置路径
      - /mnt/user/movie_data:/Downloads                     # 下载路径
    <<: *conf
    environment:
      <<: *env
      QB_TRACKERS_UPDATE_AUTO: "true"
      QB_TRACKERS_LIST_URL: https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt


  transmission:
    image: linuxserver/transmission
    container_name: transmission
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Transmission/icon.png
    <<: *conf
    environment:
      <<: *env
      TRANSMISSION_WEB_HOME: /config/src/ #optional          # webui下载地址 https://github.com/ronggang/transmission-web-control  把src目录解压出来丢进/mnt/user/appdata/mydata/tr/目录下刷新
      USER:                                                 # 登录账户
      PASS:                                                 # 登录密码
      WHITELIST:  #optional
      PEERPORT: #optional
      HOST_WHITELIST:  #optional

    volumes:
      - /mnt/user/appdata/mydata/tr:/config               # 配置路径
      - /mnt/user/movie_data:/downloads                       # 下载路径
      # - /path/to/watch/folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp


  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jackett/icon.png
    <<: *conf
    environment:
      <<: *env
      AUTO_UPDATE: "true" #optional
      # RUN_OPTS:  #optional
    volumes:
      - /mnt/user/appdata/mydata/jk:/config
      - /mnt/user/movie_data:/downloads
    ports:
      - 9117:9117
    

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    container_name: chinesesubfinder
    labels:
      - net.unraid.docker.icon=https://emojidaquan.com/Uploads/image/202105/1620699428628297.jpg
    volumes:
      - /mnt/user/appdata/mydata/csf:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/user/movie_data:/movie_data    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
    <<: *conf
    environment:
      <<: *env
    ports:
      - 19035:19035
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整

  cookiecloud:
    image: easychen/cookiecloud
    container_name: cookiecloud
    labels:
      - net.unraid.docker.icon=https://img0.baidu.com/it/u=3556978365,880012798&fm=253&fmt=auto&app=138&f=JPEG?w=240&h=240
    volumes:
      - /mnt/user/appdata/mydata/cookiecloud:/data/api/data
    ports:
      - 8088:8088
    <<: *conf
    environment:
      <<: *env

  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    labels:
      - net.unraid.docker.icon=https://emojidaquan.com/Uploads/image/202105/1620699550852160.jpg
    privileged: "true"
    ports:
      - 2017:2017
      - 20170-20172:20170-20172
    <<: *conf
    environment:
      <<: *env
      V2RAYA_LOG_FILE: "/tmp/v2raya.log"
      V2RAYA_V2RAY_BIN: "/usr/local/bin/v2ray"      # 这行注释掉默认使用xray-core
    volumes:
      - /mnt/user/appdata/mydata/v2raya:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf


  wg-easy:
    image: weejewel/wg-easy
    container_name: wg
    labels:
      - net.unraid.docker.icon=https://i.mji.rip/2023/11/07/ff7d5b863e297051d51fa340c0ad96c2.jpeg
    volumes:
      -  /mnt/user/appdata/mydata/wg:/etc/wireguard
    environment:
      WG_HOST: "you.domain.com" #你的域名
      PASSWORD: "123456" #web端登录密码
      WG_DEFAULT_DNS: "223.5.5.5,223.6.6.6"
      WG_MTU: "1420"
      WG_PERSISTENT_KEEPALIVE: "25"
      WG_PORT: "21820"  #自定义容器外端口
      WG_DEFAULT_ADDRESS: "192.168.5.x"    # wg内分配的ip段 最后一位必须是x 
      # WG_ALLOWED_IPS: ""     #默认0.0.0.0/24 允许互访ip段 
      TZ: Asia/Shanghai
    ports:
      - "21820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    <<: *conf

  alist:
    image: xhofe/alist
    container_name: alist
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Alist/icon.png
    ports:
      - 5244:5244
    volumes:
      - /mnt/user/appdata/mydata/alist:/opt/alist/data
    # - /mnt/user/movie_data:/mydata            # 这里写自己要共享的路径映射
    <<: *conf
    environment:
      <<: *env
      PUID: "0"
      PGID: "0"
      UMASK: "022"

  lucky:
    image: gdy666/lucky
    container_name: lucky
    labels:
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lucky/icon.png
    volumes:
      - /mnt/user/appdata/mydata/lucky:/goodluck
    network_mode: host
    restart: always


# 自定义网卡 驱动为桥接  
networks:
  mynet:
    name: mnet
    driver: bridge
